name: Validate Pull Request

on: pull_request

env:
  GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@lflimeira"
      - name: Update .env files
        run: ./scripts/rename-env.sh
      - name: Set npmAuthToken
        run: yarn config set npmScopes.lflimeira.npmAuthToken $GH_PAT_TOKEN
      - name: Run tests
        run: docker-compose up --exit-code-from test test
      - name: Dump Docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@lflimeira"
      - name: Update .env files
        run: ./scripts/rename-env.sh
      - name: Set npmAuthToken
        run: yarn config set npmScopes.lflimeira.npmAuthToken $GH_PAT_TOKEN
      - name: Run lint
        run: docker-compose up --exit-code-from lint lint
      - name: Dump Docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@lflimeira"
      - name: Set npmAuthToken
        run: yarn config set npmScopes.lflimeira.npmAuthToken $GH_PAT_TOKEN
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build
